name: video-downloader-bot

volumes:
  telegram-bot-api-data:

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api-server
    restart: always
    ports:
      - 8081:8081
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    env_file:
      - .env

  bot-app:
    image: python:3.11
    container_name: video-downloader-bot-app
    restart: always
    ports:
      - 8080:8080
    command: bash -c "apt-get update && apt-get install -y ffmpeg && pip3 install -r requirements.txt && python3 main.py"
    depends_on:
      - telegram-bot-api
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
