name: video-downloader-bot

services:
  server:
    image: python:3.11
    container_name: video-downloader-bot-production
    restart: always
    command: bash -c "apt-get update && apt-get install -y ffmpeg && pip3 install -r requirements.txt && python3 main.py"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Tashkent
